name: Auto Docker Build

on:
  push:
    branches:
      - release

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get install -y jq

      - name: Read version from package.json
        id: read_version
        run: |
          version=$(jq -r '.version' package.json)
          echo "Version: $version"
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Check if version tag exists
        id: check_tag
        run: |
          TAG_EXISTS=$(git ls-remote --tags origin refs/tags/v${{ steps.read_version.outputs.version }} | wc -l)
          echo "tag_exists=$TAG_EXISTS" >> $GITHUB_OUTPUT

      - name: Exit if tag already exists
        if: steps.check_tag.outputs.tag_exists != '0'
        run: |
          echo "Version v${{ steps.read_version.outputs.version }} already released. Skipping."
          exit 0

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          REPO_NAME=$(basename ${{ github.repository }})
          VERSION=${{ steps.read_version.outputs.version }}
          docker build -f Dockerfile -t ghcr.io/${{ github.repository_owner }}/$REPO_NAME:$VERSION .
          docker tag ghcr.io/${{ github.repository_owner }}/$REPO_NAME:$VERSION ghcr.io/${{ github.repository_owner }}/$REPO_NAME:latest

      - name: Push Docker image
        run: |
          REPO_NAME=$(basename ${{ github.repository }})
          VERSION=${{ steps.read_version.outputs.version }}
          docker push ghcr.io/${{ github.repository_owner }}/$REPO_NAME:$VERSION
          docker push ghcr.io/${{ github.repository_owner }}/$REPO_NAME:latest

      - name: Create Git Tag
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git tag v${{ steps.read_version.outputs.version }}
          git push origin v${{ steps.read_version.outputs.version }}

      - name: Get previous tag
        id: previous_tag
        run: |
          previous=$(git tag --sort=-creatordate | grep -v "v${{ steps.read_version.outputs.version }}" | head -n 1)
          echo "previous_tag=$previous" >> $GITHUB_OUTPUT
      - name: Get PR Info
        id: pr_info
        run: |
          PR_TITLE=$(git log --merges -1 --pretty=format:"%s" | sed -E 's/^Merge pull request #[0-9]+ from .+\/(.+)/\1/')
          PR_BODY=$(git log --merges -1 --pretty=format:"%b")
          echo "pr_title=$PR_TITLE" >> $GITHUB_OUTPUT
          echo "pr_body=$PR_BODY" >> $GITHUB_OUTPUT

      - name: Call Gemini to generate release summary
        id: ai_summary
        run: |
          VERSION=v${{ steps.read_version.outputs.version }}
          LOG=$(git log ${{ steps.previous_tag.outputs.previous_tag }}..HEAD --pretty=format:"- %s (%an)" | jq -Rs .)
          PR_TITLE=${{ steps.pr_info.outputs.pr_title }}
          PR_BODY=${{ steps.pr_info.outputs.pr_body }}
          PROMPT="Release version: $VERSION\n\nPull Request: $PR_TITLE\n\nDescription:\n$PR_BODY\n\nCommits:\n$LOG\n\nWrite a release summary including features, improvements, and bug fixes in bullet points."

          RESPONSE=$(curl -s "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key=${{ secrets.GEMINI_API_KEY }}" \
            -H 'Content-Type: application/json' \
            -X POST \
            -d '{
              "contents": [{
                "parts": [{"text": '"$(jq -Rs <<< "$PROMPT" )"'}]
              }]
            }')

          SUMMARY=$(echo "$RESPONSE" | jq -r '.candidates[0].content.parts[0].text')
          echo "title=$VERSION" >> $GITHUB_OUTPUT
          echo "summary<<EOF" >> $GITHUB_OUTPUT
          echo "$SUMMARY" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.read_version.outputs.version }}
          name: ${{ steps.ai_summary.outputs.title }}
          body: ${{ steps.ai_summary.outputs.summary }}

      - name: Update CHANGELOG.md
        run: |
          tempfile=$(mktemp)
          echo "## v${{ steps.read_version.outputs.version }} - ${{ steps.ai_summary.outputs.title }}" >> $tempfile
          echo "" >> $tempfile
          echo "${{ steps.ai_summary.outputs.summary }}" >> $tempfile
          echo "" >> $tempfile
          [ -f CHANGELOG.md ] && cat CHANGELOG.md >> $tempfile
          mv $tempfile CHANGELOG.md
          cat CHANGELOG.md

      - name: Commit and push CHANGELOG.md
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add CHANGELOG.md
          git commit -m "Update CHANGELOG.md for v${{ steps.read_version.outputs.version }}"
          git push origin release
